version: "2"
services:
  apostrophe:
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data/uploads:/app/public/uploads
      - ./data/backups:/app/backups
    environment:
      - APOS_MONGODB_URI=mongodb://mongo:27017/db
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rise8
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./mongod.conf:/etc/mongod.conf
    ports:
      - "27017:27017"
