name: Deploy Website

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy in'
        type: environment
        required: true
jobs:
  build:
    environment: ${{ inputs.environment }}
    env:
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-gov-west-1
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get Kubeconfig
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name ${{ secrets.CLUSTER_NAME }}
    - name: Deploy Website
      run: |
        EXPRESS_SECRET=$(openssl rand -hex 24)
        helm upgrade --install rise8-website helm-chart                      \
          -f helm-chart/rise8-website-${{ inputs.environment }}.values.yaml  \
          --set "express.secret=$EXPRESS_SECRET"                             \
          --set "existingClaim=rise8-website-${{ inputs.environment }}"
