name: Update ECR Secret

on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    env:
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-gov-west-1
    strategy:
      matrix:
        namespace: ["website-staging", "website-prod"]
    runs-on: ubuntu-latest
    steps:
    - name: Get Kubeconfig
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name ${{ secrets.CLUSTER_NAME }}
    - name: Create Secret
      run: |
        DOCKER_PASSWORD=$(aws ecr get-login-password)
        echo "::add-mask::$DOCKER_PASSWORD"

        kubectl create secret docker-registry regcred \
          --docker-server=${{ secrets.ECR_URL }} \
          --docker-username=AWS \
          --docker-password=$DOCKER_PASSWORD \
          --namespace=${{ matrix.namespace }} \
          --dry-run=client -o yaml | kubectl apply -f -
