name: Update ECR Secret

on:
  schedule:
    - cron:  '0 0,12 * * *'
  workflow_dispatch:

jobs:
  build:
    env:
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-gov-west-1
    strategy:
      matrix:
        namespace: ["staging"]
    runs-on: ubuntu-latest
    steps:
    - name: Get Kubeconfig
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name ${{ secrets.CLUSTER_NAME }}
    - name: Create Secret
      run: |
        kubectl create secret docker-registry regcred \
          --docker-server=${{ secrets.ECR_URL }} \
          --docker-username=AWS \
          --docker-password=$(aws ecr get-login-password) \
          --namespace=${{ matrix.namespace }}